language: php
php:
    - "5.6"
    - "7.0"

install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction

script: ant -keep-going
