name: contao-community-alliance/url-builder

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.2
            output: '-o default'
            phpcq_install: 'update'

    steps:
      - name: PHP ${{ matrix.php }} Pull source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # see https://github.com/shivammathur/setup-php
      - name: PHP ${{ matrix.php }} Setup PHP.
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: PHP ${{ matrix.php }} Cache composer cache directory
        uses: actions/cache@v3
        env:
          cache-name: composer-cache-dir
        with:
          path: ~/.cache/composer
          key: ${{ runner.os }}-${{ matrix.php }}-build-${{ env.cache-name }}

      - name: PHP ${{ matrix.php }} Cache vendor directory
        uses: actions/cache@v3
        env:
          cache-name: composer-vendor
        with:
          path: vendor
          key: ${{ runner.os }}-${{ matrix.php }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php }}-build-${{ env.cache-name }}-

      - name: PHP ${{ matrix.php }} Cache phpcq directory
        uses: actions/cache@v3
        env:
          cache-name: phpcq
        with:
          path: .phpcq
          key: ${{ runner.os }}-${{ matrix.php }}-build-${{ env.cache-name }}-${{ hashFiles('**/.phpcq.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php }}-build-${{ env.cache-name }}-

      - name: PHP ${{ matrix.php }} Install composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: PHP ${{ matrix.php }} Install phpcq toolchain
        run: ./vendor/bin/phpcq ${{ matrix.phpcq_install }} -v

      - name: PHP ${{ matrix.php }} Run tests
        run: ./vendor/bin/phpcq run -v ${{ matrix.output }}

      - name: PHP ${{ matrix.php }} Upload build directory to artifact
        uses: actions/upload-artifact@v3
        if: ${{ success() }} || ${{ failure() }}
        with:
          name: phpcq-builds-php-${{ matrix.php }}
          path: .phpcq/build/
